# implementation of methods causing errors
# sorted after likelihood of occuring
# TheErrorLandscape

class ErrorExamples:
    
    filledDict = {
        'one': 1,
        'two': 2
    }

    arr = ['I', 'am', 'an', 'array']
    
    def __init__(self) -> None:
        pass  

    # 10.02%
    def nameError(self):
        print(hello)

    # 8.92%
    def typeError1(self, string: str):
        print(string)

    def typeError2(string: str):
        print(string)

    # 4.46%
    def keyError(self):
        print(self.filledDict['three'])

    # 4.49%
    def indexError(self):
        print(self.arr[len(self.arr)])
    
    # 2.62%
    # probably renamed in ModuleNotFoundError
    def importError(self):
        import fail
    
    # 1.92%
    def attributeError(self):
        x = 10
        x.append(5)

    # 1.31%
    # cant find this one yet
    def runtimeError(self):
        pass

    # 1.07%
    def unboundLocalError(self):
        print(msg)
        msg = 'Hello' 

    # 0.75%
    def valueError(self):
        int('string')

    # 0.20%
    def zeroDivisionError(self):
        10/0

    # 0.05%
    def assertionError(self):
        x, y = 10, 5
        assert x == y

    # 0.01%
    def exception(self):
        raise Exception('Crash')

    # 0.00%
    # cant reproduce this one
    def memoryError(self):
        x = 2
        while True:
            x = x**10
            print(x)

    # 0.00%
    # lost the csv
    def stopIteration(self):
        data = 'test.csv'
        c = csv.DictReader(io.StringIO(data), dialect=csv.excel_tab)
        keys = next(c) 

    def recursionError(self):
        return self.recursionError()

    # def indentationError(self):
    # print('error')

errorExamples = ErrorExamples()

# NameError: name 'hello' is not defined
# errorExamples.nameError()

# TypeError: typeError1() missing 1 required positional argument: 'string'
# errorExamples.typeError1()

# TypeError: typeError2() takes 1 positional argument but 2 were given
# errorExamples.typeError2('foo')

# IndexError: list index out of range
# errorExamples.indexError()

# UnboundLocalError: local variable 'msg' referenced before assignment
# errorExamples.unboundLocalError()

# ModuleNotFoundError: No module named 'fail'
# errorExamples.importError()

# AttributeError: 'int' object has no attribute 'append'
# errorExamples.attributeError()

# ValueError: invalid literal for int() with base 10: 'string'
# errorExamples.valueError()

# ZeroDivisionError: division by zero
# errorExamples.zeroDivisionError()

# AssertionError
# errorExamples.assertionError()

# Exception: Crash
# errorExamples.exception()

# cant be reproduced for now
# errorExamples.memoryError()

# StopIteration
# errorExamples.stopIteration()

# RecursionError: maximum recursion depth exceeded
# errorExamples.recursionError()

# IndentationError: expected an indented block
# errorExamples.indentationError()

try:
    errorExamples.recursionError()
except ZeroDivisionError:
    print('Error')
else:
    print('Could not catch any error')
finally:
    print('Guarding done') 